
name: Build debug
on:
    push:
        branches:
            - develop
            - staging
            - sandbox
            - feature/202509/mabuchi/**

#env:
#    ASSEMBLE_DEVELOP_DEBUG: "assembleDevelopDebug"
#    ASSEMBLE_STAGING_DEBUG: "assembleStagingDebug"
#    ASSEMBLE_SANDBOX_DEBUG: "assembleSandboxDebug"

jobs:
    build-debug:
        runs-on: ubuntu-latest
        # Releases への公開に書き込み権限が必要
        permissions:
            contents: write
        defaults:
            run:
                working-directory: 'myapp'
        env:
            BRANCH: 'production'
            BRANCH_CAMEL: 'Production'
            BUILD_TYPE: 'release'
            BUILD_TYPE_CAMEL: 'Release'
        steps:
            - name: 'Set env by branch'
              if: github.ref_name == 'develop'
              run: | 
                echo "BRANCH=develop" >> $GITHUB_ENV
                echo "BRANCH_CAMEL=Develop" >> $GITHUB_ENV
                echo "BUILD_TYPE=debug" >> $GITHUB_ENV
                echo "BUILD_TYPE_CAMEL=Debug" >> $GITHUB_ENV

            - name: 'Checkout'
              uses: actions/checkout@v5

            - name: "Setup Java"
              uses: actions/setup-java@v5
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: 'gradle'

            - name: 'Get short SHA'
              id: get_short_sha
              run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> "$GITHUB_ENV"
            - run: echo "SHA:${{ env.SHORT_SHA }}"

            - name: 'Restore key stores'
              run: echo "${{ secrets.GRADLE_PROPERTIES_BASE64 }}" | base64 -d > app/gradle.properties
            - run: echo "${{ secrets.DEVELOP_KEY_BASE64 }}" | base64 -d > app/developKey.jks
            - run: echo "${{ secrets.STAGING_KEY_BASE64 }}" | base64 -d > app/stagingKey.jks
            - run: echo "${{ secrets.SANDBOX_KEY_BASE64 }}" | base64 -d > app/sandboxKey.jks
            - run: echo "${{ secrets.PRODUCTION_KEY_BASE64 }}" | base64 -d > app/productionKey.jks
            - run: ls -l app

            - run: chmod +x ./gradlew

            - run: echo "VERSION_NAME=$( ./gradlew -q app:printVersionName )" >> $GITHUB_ENV
            - run: echo "version:v.${{ env.VERSION_NAME }}"

            - run: echo "ASSEMBLE_TASK=assemble${{ env.BRANCH_CAMEL }}${{ env.BUILD_TYPE_CAMEL }}" >> $GITHUB_ENV

            - run: ./gradlew ${{ env.ASSEMBLE_TASK }} --no-daemon

            - run: ls -l app/build/outputs/apk
          #  - run: ls -l app/build/outputs/apk/develop
            - run: ls -l "app/build/outputs/apk/${{ env.BRANCH }}/${{ env.BUILD_TYPE }}"

            - run: echo ${{ github.ref_name }}
            - run: echo ${{ github.ref }}

            - name: 'Github Release'
              uses: softprops/action-gh-release@v2
              with:
                name: 'v.${{ env.VERSION_NAME }}-${{ env.BRANCH }}-${{ env.BUILD_TYPE }}'
                body: ''
                tag_name: 'v.${{ env.VERSION_NAME }}-${{ env.BRANCH }}-${{ env.BUILD_TYPE }}'
                files: |
                    myapp/app/build/outputs/apk/${{ env.BRANCH }}/${{ env.BUILD_TYPE}}/*.apk


    
