
name: Merge debug
on:
    workflow_dispatch:
      inputs:
        target-environment:
          type: choice
          description: 'feature ブランチで動かす場合に指定'
          options:
            - "develop"
            - "staging"
            - "sandbox"
    push:
        branches:
            - develop
            - staging
            - sandbox
#            - feature/202509/mabuchi/act1

jobs:
    build-debug:
        runs-on: ubuntu-latest
        # Releases への公開に書き込み権限が必要
        permissions:
            contents: write
        defaults:
            run:
                working-directory: 'myapp'
        env:
            BRANCH: 'production'
            BRANCH_CAMEL: 'Production'
            BUILD_TYPE: 'debug'
            BUILD_TYPE_CAMEL: 'Debug'

        steps:
            - name: 'Checkout'
              uses: actions/checkout@v5

            - name: "Setup Java"
              uses: actions/setup-java@v5
              with:
                java-version: '17'
                distribution: 'temurin'
            
            - name: 'Setup gradle'
              uses: gradle/actions/setup-gradle@v4

            - run: echo 'github.ref_name:${{ github.ref_name }}'

            - name: 'develop ブランチ用の env を設定'
              if: github.ref_name == 'develop' || inputs.target-environment == 'develop'
              run: | 
                echo "BRANCH=develop" >> $GITHUB_ENV
                echo "BRANCH_CAMEL=Develop" >> $GITHUB_ENV

            - name: 'staging ブランチの用の env を設定'
              if: github.ref_name == 'staging' || inputs.target-environment == 'staging'
              run: | 
                echo "BRANCH=staging" >> $GITHUB_ENV
                echo "BRANCH_CAMEL=Staging" >> $GITHUB_ENV

            - name: 'sandbox ブランチの用の env を設定'
              if: github.ref_name == 'sandbox' || inputs.target-environment == 'sandbox'
              run: | 
                echo "BRANCH=sandbox" >> $GITHUB_ENV
                echo "BRANCH_CAMEL=Sandbox" >> $GITHUB_ENV

            # - name: 'ショート SHA を取得'
            #   id: get_short_sha
            #   run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> "$GITHUB_ENV"
            # - run: echo "SHA:${{ env.SHORT_SHA }}"

            - name: 'キーストアを復元'
              run: |
                echo "${{ secrets.GRADLE_PROPERTIES_BASE64 }}" | base64 -d > app/gradle.properties
                echo "${{ secrets.DEVELOP_KEY_BASE64 }}" | base64 -d > app/developKey.jks
                echo "${{ secrets.STAGING_KEY_BASE64 }}" | base64 -d > app/stagingKey.jks
                echo "${{ secrets.SANDBOX_KEY_BASE64 }}" | base64 -d > app/sandboxKey.jks
                echo "${{ secrets.PRODUCTION_KEY_BASE64 }}" | base64 -d > app/productionKey.jks

            # - name: 'キーストア復元の確認(*要削除*)'
            #   run: ls -l app

            - run: chmod +x ./gradlew

            - name: 'versionName を取得'
              run: echo "VERSION_NAME=$( ./gradlew -q app:printVersionName )" >> $GITHUB_ENV
   
            # - name: 'versionName の確認(*要削除*)'
            #   run: echo "version:v${{ env.VERSION_NAME }}"

            - name: './gradlew assemble<Branch><BuildType>'
              run: ./gradlew assemble${{ env.BRANCH_CAMEL }}${{ env.BUILD_TYPE_CAMEL }} --no-daemon

            - name: 'APK をリネーム'
              run: |
                APK_NAME="app/build/outputs/apk/${{ env.BRANCH }}/${{ env.BUILD_TYPE}}/app-${{ env.BRANCH }}-${{ env.BUILD_TYPE}}.apk"
                NEW_APK_NAME="${APK_NAME//app-/v${{ env.VERSION_NAME }}-}"
                mv $APK_NAME $NEW_APK_NAME
                ls -l "app/build/outputs/apk/${{ env.BRANCH }}/${{ env.BUILD_TYPE }}"

            - name: 'Github Release に APK を配置する'
              uses: softprops/action-gh-release@v2
              with:
                name: 'v${{ env.VERSION_NAME }}-${{ env.BRANCH }}-${{ env.BUILD_TYPE }}'
                body: ''
                tag_name: 'v${{ env.VERSION_NAME }}-${{ env.BRANCH }}-${{ env.BUILD_TYPE }}'
                files: |
                    myapp/app/build/outputs/apk/${{ env.BRANCH }}/${{ env.BUILD_TYPE}}/*.apk


            - run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV

            - name: 'Slack'
              uses: rtCamp/action-slack-notify@v2.2.0
              if: success()
              env:
                SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'
                SLACK_TITLE: '通知だよ'
                SLACK_MESSAGE: '${{ env.BRANCH }} マージ&ビルド成功 [ ${{ env.REPOSITORY_NAME }} ]'


    
